spring:
  application:
    name: car-service-facade
  cloud:
    discovery:
      enabled: true
      

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

server:
  port: 8080  
