#service manifest for kubernetes
apiVersion: v1
kind: Service
metadata:
  name: echo-rest-service
  labels:
    app: echo-rest-example
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echo-rest-example
    tier: backend